import { prisma } from '@/lib/prisma'
import { generateNewsletterHtml } from '@/lib/newsletter-templates'

export async function getNewsletterSettings() {
    let settings = await prisma.newsletterSetting.findUnique({
        where: { id: 'GLOBAL' }
    })

    if (!settings) {
        settings = await prisma.newsletterSetting.create({
            data: {
                id: 'GLOBAL',
                autoSendEnabled: false,
                autoSendDelayMinutes: 15,
                senderName: 'IA Solutions',
                senderEmail: process.env.SMTP_USER || 'newsletter@partnersiasolutions.com',
                defaultCrossSellEnabled: true
            }
        })
    }

    return settings
}

export async function createCampaignFromPost(post: any) {
    const settings = await getNewsletterSettings()
    
    // Check if campaign already exists for this post
    const existing = await prisma.newsletterCampaign.findFirst({
        where: { sourcePostId: post.id }
    })
    
    if (existing) {
        console.log(`Campaign already exists for post ${post.id}`)
        return existing
    }

    const scheduledFor = settings.autoSendEnabled 
        ? new Date(Date.now() + settings.autoSendDelayMinutes * 60000)
        : null

    const status = settings.autoSendEnabled ? 'SCHEDULED' : 'DRAFT'

    // Extract intro from content (first 200 chars or first paragraph)
    const plainContent = post.content.replace(/<[^>]*>?/gm, '')
    const introText = post.introText || plainContent.substring(0, 250) + '...'

    const campaign = await prisma.newsletterCampaign.create({
        data: {
            title: `Auto: ${post.title}`,
            subject: post.title,
            preheader: post.category || 'Novedades en IA',
            introText: introText,
            content: post.content,
            heroImage: post.coverImage,
            primaryCtaText: 'Leer artículo completo',
            primaryCtaUrl: `https://partnersiasolutions.com/noticias/${post.slug}`,
            status: status,
            scheduledFor: scheduledFor,
            autoGenerated: true,
            sourcePostId: post.id,
            showInterests: settings.defaultCrossSellEnabled,
            // We could add default recommended solutions here if needed
            recommendedSolutions: [] 
        }
    })

    console.log(`Auto-generated campaign ${campaign.id} for post ${post.id} (Status: ${status})`)
    return campaign
}
