const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
    console.log('--- Real Delivery Test (Manual) ---')
    
    // 1. Create a test subscriber with a real email (user should provide one)
    const testEmail = process.argv[2]
    if (!testEmail) {
        console.error('Please provide a test email: node src/scripts/test_real_delivery.js email@example.com')
        process.exit(1)
    }

    const subscriber = await prisma.newsletterSubscriber.upsert({
        where: { email: testEmail },
        update: { isActive: true },
        create: {
            email: testEmail,
            isActive: true,
            consentGdpr: true,
            consentDate: new Date(),
            unsubscribeToken: 'test-token-' + Date.now()
        }
    })
    console.log(`✅ Test subscriber ready: ${subscriber.email}`)

    // 2. Create a campaign
    const campaign = await prisma.newsletterCampaign.create({
        data: {
            title: '[TEST REAL] Newsletter IA Solutions',
            subject: '¡Bienvenido a la Newsletter de IA Solutions!',
            preheader: 'Tu dosis semanal de inteligencia artificial',
            introText: 'Este es un envío de prueba real para verificar la entrega en inbox y el diseño.',
            content: '<p>Hola,</p><p>Esta es la nueva newsletter automatizada de Partners IA Solutions. Si estás leyendo esto, el sistema de envío real está funcionando correctamente.</p>',
            status: 'DRAFT',
            autoGenerated: false,
            showInterests: true
        }
    })
    console.log(`✅ Campaign created: ${campaign.id}`)

    console.log('\n--- NEXT STEPS ---')
    console.log(`1. Go to http://localhost:3000/admin/newsletter/campaigns`)
    console.log(`2. Open the campaign: ${campaign.title}`)
    console.log(`3. Click on "Enviar a suscriptores activos" (Ensure only this test user is active or use a filter if implemented)`)
    console.log(`4. Verify delivery in ${testEmail}`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
