const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
    // 1. Create Post
    const post = await prisma.newsPost.create({
        data: {
            title: 'Test Post Automation ON',
            slug: 'test-post-automation-on-' + Date.now(),
            content: '<p>Este es un post de prueba para validar que con autoSendEnabled en ON se crea una campaña en SCHEDULED.</p>',
            published: true, // Directly published to trigger automation in my simulation
            category: 'IA Test'
        }
    })
    console.log('✅ Created and Published post:', post.id)

    // 2. Simulate Automation Trigger
    const settings = await prisma.newsletterSetting.findUnique({ where: { id: 'GLOBAL' } })
    
    const status = 'SCHEDULED'
    const scheduledFor = new Date(Date.now() + settings.autoSendDelayMinutes * 60000)

    const plainContent = post.content.replace(/<[^>]*>?/gm, '')
    const introText = plainContent.substring(0, 250) + '...'

    const campaign = await prisma.newsletterCampaign.create({
        data: {
            title: `Auto: ${post.title}`,
            subject: post.title,
            preheader: post.category || 'Novedades en IA',
            introText: introText,
            content: post.content,
            heroImage: post.coverImage,
            primaryCtaText: 'Leer artículo completo',
            primaryCtaUrl: `https://partnersiasolutions.com/noticias/${post.slug}`,
            status: status,
            scheduledFor: scheduledFor,
            autoGenerated: true,
            sourcePostId: post.id,
            showInterests: settings.defaultCrossSellEnabled,
            recommendedSolutions: [] 
        }
    })

    console.log('✅ Campaign Created (ON):', {
        id: campaign.id,
        status: campaign.status,
        scheduledFor: campaign.scheduledFor,
        sourcePostId: campaign.sourcePostId
    })

    return { postId: post.id, campaignId: campaign.id }
}

main().catch(console.error).finally(() => prisma.$disconnect())
