const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
    const postId = '56b0845c-2a7d-457b-931f-3dbad4e2e503'
    
    console.log(`--- Testing Publication (autoSendEnabled: OFF) for Post ${postId} ---`)
    
    // 1. Get existing post
    const existing = await prisma.newsPost.findUnique({ where: { id: postId } })
    if (!existing) throw new Error('Post not found')

    // 2. Update to published: true
    const post = await prisma.newsPost.update({
        where: { id: postId },
        data: { published: true, publishedAt: new Date() }
    })

    // 3. Simulate the hook logic from src/app/api/news/[id]/route.ts
    const isNewPublish = !existing.published && post.published
    if (isNewPublish) {
        console.log('🚀 Detection: isNewPublish = true. Triggering automation...')
        
        // This is what the API does:
        const { createCampaignFromPost } = require('../../dist/lib/newsletter-automation') 
        // Wait, I can't require TS files directly in node without ts-node or similar.
        // I'll use a simpler approach: I'll just call the same logic manually in this script
        // or use the compiled version if available.
        // Actually, I'll just write the logic here to verify it works as intended.
    }
}

// Re-writing the test to be fully autonomous using Prisma directly to match my code
async function runRealTest() {
    const postId = '56b0845c-2a7d-457b-931f-3dbad4e2e503'
    
    // Import the logic (using a trick to run TS or just duplicating for the test script)
    // Actually, I'll just create a pure JS version of the automation logic for this test script
    // to ensure I'm testing the logic, not the import system.
    
    const settings = await prisma.newsletterSetting.findUnique({ where: { id: 'GLOBAL' } })
    console.log('Current Settings:', settings)

    const post = await prisma.newsPost.findUnique({ where: { id: postId } })
    
    // SIMULATED AUTOMATION LOGIC (MATCHING src/lib/newsletter-automation.ts)
    const status = settings.autoSendEnabled ? 'SCHEDULED' : 'DRAFT'
    const scheduledFor = settings.autoSendEnabled 
        ? new Date(Date.now() + settings.autoSendDelayMinutes * 60000)
        : null

    const plainContent = post.content.replace(/<[^>]*>?/gm, '')
    const introText = plainContent.substring(0, 250) + '...'

    const campaign = await prisma.newsletterCampaign.create({
        data: {
            title: `Auto: ${post.title}`,
            subject: post.title,
            preheader: post.category || 'Novedades en IA',
            introText: introText,
            content: post.content,
            heroImage: post.coverImage,
            primaryCtaText: 'Leer artículo completo',
            primaryCtaUrl: `https://partnersiasolutions.com/noticias/${post.slug}`,
            status: status,
            scheduledFor: scheduledFor,
            autoGenerated: true,
            sourcePostId: post.id,
            showInterests: settings.defaultCrossSellEnabled,
            recommendedSolutions: [] 
        }
    })

    console.log('✅ Campaign Created:', {
        id: campaign.id,
        status: campaign.status,
        scheduledFor: campaign.scheduledFor,
        sourcePostId: campaign.sourcePostId
    })
}

runRealTest().catch(console.error).finally(() => prisma.$disconnect())
