-- CreateTable
CREATE TABLE `NewsletterSubscriber` (
    `id` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `sourceLocation` VARCHAR(191) NULL,
    `sourceUrl` VARCHAR(191) NULL,
    `consentAccepted` BOOLEAN NOT NULL DEFAULT true,
    `consentAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `unsubscribeToken` VARCHAR(191) NOT NULL,
    `confirmedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `NewsletterSubscriber_email_key`(`email`),
    UNIQUE INDEX `NewsletterSubscriber_unsubscribeToken_key`(`unsubscribeToken`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NewsletterCampaign` (
    `id` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `subject` VARCHAR(191) NOT NULL,
    `preheader` VARCHAR(191) NULL,
    `introText` LONGTEXT NULL,
    `heroImage` TEXT NULL,
    `primaryCtaText` VARCHAR(191) NULL,
    `primaryCtaUrl` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'DRAFT',
    `scheduledFor` DATETIME(3) NULL,
    `sentAt` DATETIME(3) NULL,
    `autoGenerated` BOOLEAN NOT NULL DEFAULT false,
    `sourcePostId` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NewsletterCampaignLog` (
    `id` VARCHAR(191) NOT NULL,
    `campaignId` VARCHAR(191) NOT NULL,
    `subscriberId` VARCHAR(191) NOT NULL,
    `deliveryStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    `provider` VARCHAR(191) NULL,
    `providerMsgId` VARCHAR(191) NULL,
    `openedAt` DATETIME(3) NULL,
    `clickedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NewsletterSetting` (
    `id` VARCHAR(191) NOT NULL DEFAULT 'GLOBAL',
    `autoSendEnabled` BOOLEAN NOT NULL DEFAULT false,
    `autoSendDelayMinutes` INTEGER NOT NULL DEFAULT 15,
    `senderName` VARCHAR(191) NULL,
    `senderEmail` VARCHAR(191) NULL,
    `brandingLogo` VARCHAR(191) NULL,
    `footerText` TEXT NULL,
    `defaultCrossSellEnabled` BOOLEAN NOT NULL DEFAULT true,
    `doubleOptInEnabled` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `NewsletterCampaignLog` ADD CONSTRAINT `NewsletterCampaignLog_campaignId_fkey` FOREIGN KEY (`campaignId`) REFERENCES `NewsletterCampaign`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NewsletterCampaignLog` ADD CONSTRAINT `NewsletterCampaignLog_subscriberId_fkey` FOREIGN KEY (`subscriberId`) REFERENCES `NewsletterSubscriber`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

